language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - php -S localhost:8080 -t ./testapp" > /dev/null 2> server.log &
  - ./vendor/bin/behat --strict

after_failure:
  - echo "Tests failed - httpd log follows"
  - echo "================================"
  - cat server.log
